# Generated by Django 2.0.2 on 2018-04-27 18:30

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180427_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_markdown.models.MarkdownField(),
        ),
    ]
